### ISSUE TITLE
Confused about the output file

### ISSUE THREAD

**Issue by isJHan** [endomapper/EM_Dataset-PhotometricCalibration#1]
What's mean of d and sigma at Sect. Calibration results in README?

In your paper, the 'Simplified photometric model' you used has no variable d which equals to z axis of the camera.

Thanks for your help!

**Comment by vmbatlle** [comment]
Hi,

The `sigma` value corresponds to the "main intensity value" of the light source, we use symbol $\sigma_0$ in equation (3) of [Azagra et al.](https://arxiv.org/pdf/2204.14240.pdf) and also in equations (1) and (5) of [Batlle et al.](https://arxiv.org/pdf/2204.09083.pdf). Altough we usually assume it to be $\sigma_0 = 1$ so it disapears from some equations, for simplicity.

The `D` value is the "principal direction" of the light source. It appears as $\mathbf{D}$ in equation (3) of Azagra et al. and as $\mathbf{d}_l$ in equation (2) of Batlle et al. In Batlle et al. paper we set $\mathbf{d}_l = Z$ and also $\mathbf{x}_l = \mathbf{x}_c$ by using a [`NormalizedZFixedSpotLightSource`](https://github.com/endomapper/EM_Dataset-PhotometricCalibration/blob/fdeabb96135849fbe56e3b3f46500459311b3b53/calibration/lights.py#L305C7-L305C38).

I will update the code in the next few days to expose the `NormalizedZFixedSpotLightSource` through the configuration file ([calibration/config_globals.py](https://github.com/endomapper/EM_Dataset-PhotometricCalibration/blob/fdeabb96135849fbe56e3b3f46500459311b3b53/calibration/config_globals.py#L17)).

Thank you for pointing this out

**Comment by isJHan** [comment]
Thank you!

**Comment by isJHan** [comment]
Have you finished organizing the code, please?

**Comment by vmbatlle** [comment]
Hello, I apologize for leaving this issue unattended. Please try switching to the `fix-NZFSLS` branch now and running the `./run` script. Let me know if this provides the expected calibration result: $\mathbf{d}_l = Z$ and $\mathbf{x}_l = \mathbf{x}_c$.

**Comment by isJHan** [comment]
Thanks, I will try it.
