### ISSUE TITLE
partially initialized module 'vignettings' has no attribute 'Base' (most likely due to a circular import)

### ISSUE THREAD

**Issue by isJHan** [endomapper/EM_Dataset-PhotometricCalibration#3]
### Environment:
`python 3.9.19`
```
Package         Version
 --------------- ----------- 
cycler          0.12.1
fonttools       4.53.0
kiwisolver      1.4.5
matplotlib      3.5.1
nptyping        1.4.4
numpy           1.22.2
opencv-python   3.4.17.63
packaging       24.0
pillow          10.3.0
pip             24.0
pyparsing       3.1.2
python-dateutil 2.9.0.post0
scipy           1.8.0
setuptools      70.0.0
six             1.16.0
tqdm            4.61.2
typish          1.9.3
wheel           0.43.0
```

I want ot test my own camera geometrical.xml file, so I add code below into `calibration/cameras.py`.
```python
if __name__ == "__main__":
    # test 
    camera = Factory.fromXML("demo_data/01/01_geometrical.xml", "demo_data/01/01_mask.png")
    
```

When I run this code by `python calibration/cameras.py`, there is an AttributeError, `AttributeError: partially initialized module 'vignettings' has no attribute 'Base' (most likely due to a circular import)`.

Thanks very much.

### Appendix
My camera geometrical.xml file is shown below.
```xml
<geometrical>
    <vicalib>
        <camera_model name="camera0" index="0" serialno="0" type="calibu_fu_fv_u0_v0" version="2.0">
            <width> 672 </width>
            <height> 512 </height>
            <!-- Pattern parameters ordered as per type name. -->
            <!-- [ columns; rows; grid spacing (mm); large radius (mm); small radius (mm) ] -->
            <params> [ 383.6930755563; 383.7529328059; 339.5271329985; 271.8234458423 ] </params>
        </camera_model>
        <pose>
            <!-- Pattern pose. World from Pattern point transfer. 3x4 matrix -->
            <T_wc> [ 1, 0, 0, 0; 0, 1, 0, 0; 0, 0, 1, 0 ] </T_wc>
        </pose>
    </vicalib>
</geometrical>
```

**Comment by isJHan** [comment]
Hello, are you there?

**Comment by vmbatlle** [comment]
Hello,
There was indeed a circular import, thank you for reporting this. You can check the fix provided above.
The code is written to be used as is, so you should expect some further issues if you modify it. I'd be happy to help, but I don't usually have time to review GitHub issues. Thank you for your understanding.
Best,

**Comment by isJHan** [comment]
> Hello, There was indeed a circular import, thank you for reporting this. You can check the fix provided above. The code is written to be used as is, so you should expect some further issues if you modify it. I'd be happy to help, but I don't usually have time to review GitHub issues. Thank you for your understanding. Best,

Thanks for your time. I have already fixed this bug.

I'd be happy to refine the code while trying to run this on my computer if there are other issues.

Thanks for your time again!
